image: alpine:latest  # lightweight build image

pages:
  stage: deploy
  script:
    - echo "Nothing to build, publishing /public"
  artifacts:
    paths:
      - public
  only:
    - main  # or "master" if your default branch is master
